Repository stefvanhouten/WebdevPeriod3, pull requests merged in 2021-04, with the labels that each got.

#52 Add the ability to post comments
  WebdevPeriod3/Controllers/DashboardController.cs
  WebdevPeriod3/Models/CommentDto.cs
  WebdevPeriod3/Models/FlagCommentDto.cs
  WebdevPeriod3/Models/HydratedComment.cs
  WebdevPeriod3/Services/CommentRepository.cs
  WebdevPeriod3/Services/DapperCommentStore.cs
  WebdevPeriod3/Services/ProductRepository.cs
  WebdevPeriod3/Startup.cs
  WebdevPeriod3/ViewModels/CommentViewModel.cs
  WebdevPeriod3/ViewModels/PostViewModel.cs
  WebdevPeriod3/Views/Dashboard/ViewPost.cshtml
  WebdevPeriod3/Views/Dashboard/_Comment.cshtml
  WebdevPeriod3/Views/Dashboard/_CommentForm.cshtml
  WebdevPeriod3/Views/Dashboard/_FlagCommentButton.cshtml
  WebdevPeriod3/wwwroot/js/comments.js
Labels: enhancement

#51 Roles management
  WebdevPeriod3/Areas/Identity/Services/UserRoleRepository.cs
  WebdevPeriod3/Controllers/AdminController.cs
  WebdevPeriod3/Controllers/RoleController.cs
  WebdevPeriod3/Models/UserTableRowModel.cs
  WebdevPeriod3/Views/Admin/Users.cshtml
  WebdevPeriod3/Views/Admin/_UserTableRow.cshtml
  WebdevPeriod3/wwwroot/js/rolemanagement.js
Labels: bug, enhancement

#54 Fix the logo link
  WebdevPeriod3/Views/Shared/_NavBar.cshtml
Labels: bug

#55 Endpoint authorization
  WebdevPeriod3/Areas/Identity/Controllers/ProfileController.cs
  WebdevPeriod3/Controllers/AdminController.cs
  WebdevPeriod3/Controllers/DashboardController.cs
  WebdevPeriod3/Controllers/HomeController.cs
Labels: enhancement

#56 Add functionality to the dashboard's search bar
  WebdevPeriod3/Controllers/DashboardController.cs
  WebdevPeriod3/Services/ProductRepository.cs
  WebdevPeriod3/ViewModels/DashboardViewModel.cs
  WebdevPeriod3/Views/Dashboard/Index.cshtml
Labels: enhancement
