Repository stefvanhouten/WebdevPeriod3, pull requests merged in 2021-03, with the labels that each got.

#20 Change the profile page's title to "Profile"
  WebdevPeriod3/Areas/Identity/Views/Profile/Index.cshtml
Labels: bug

#18 Authentication redirects
  WebdevPeriod3/Areas/Identity/Controllers/LoginController.cs
  WebdevPeriod3/Areas/Identity/Controllers/RegistrationController.cs
  WebdevPeriod3/Areas/Identity/Models/LoginDto.cs
  WebdevPeriod3/Areas/Identity/Models/RegistrationDto.cs
  WebdevPeriod3/Areas/Identity/Views/Login/Index.cshtml
  WebdevPeriod3/Areas/Identity/Views/Registration/Index.cshtml
  WebdevPeriod3/Startup.cs
Labels: bug, enhancement

#17 Navigation refactoring
  WebdevPeriod3/Views/Shared/_Layout.cshtml
  WebdevPeriod3/Views/Shared/_NavBar.cshtml
  WebdevPeriod3/Views/Shared/_Navigation.cshtml
  WebdevPeriod3/wwwroot/js/site.js
Labels: bug, enhancement

#22 Remove extraneous profile features
  WebdevPeriod3/Areas/Identity/Views/Profile/Index.cshtml
Labels: bug, enhancement

#24 JS refactor
  WebdevPeriod3/Views/Dashboard/CreatePost.cshtml
  WebdevPeriod3/libman.json
  WebdevPeriod3/wwwroot/js/subsystemlist.js
Labels: enhancement

#28 Add products in a single transaction
  WebdevPeriod3/Controllers/DashboardController.cs
  WebdevPeriod3/Services/DapperProductStore.cs
Labels: bug, enhancement

#34 Remove Index Action from Admin
  WebdevPeriod3/Controllers/AdminController.cs
Labels: bug

#35 Add authorization to certain pages
  WebdevPeriod3/Controllers/AdminController.cs
  WebdevPeriod3/Controllers/DashboardController.cs
Labels: bug, enhancement

#36 Fix a bug which made PostCSS ignore cshtml files
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: bug

#38 Improve the registration link
  WebdevPeriod3/Areas/Identity/Views/Login/Index.cshtml
Labels: bug, enhancement

#30 Make the dashboard link in the navigation absolute
  WebdevPeriod3/Views/Shared/_Navigation.cshtml
Labels: bug

#43 Remove content-adding call
  WebdevPeriod3/wwwroot/js/subsystemlist.js
Labels: bug

#46 Add image uploads
  WebdevPeriod3/Controllers/DashboardController.cs
  WebdevPeriod3/Entities/Product.cs
  WebdevPeriod3/Migrations/20210321_AddProductImage.cs
  WebdevPeriod3/Models/ProductDto.cs
  WebdevPeriod3/Services/ProductRepository.cs
  WebdevPeriod3/Utilities/ExpressionExtensions.cs
  WebdevPeriod3/ViewModels/PostViewModel.cs
  WebdevPeriod3/Views/Dashboard/CreateProduct.cshtml
  WebdevPeriod3/Views/Dashboard/Index.cshtml
  WebdevPeriod3/Views/Dashboard/ViewPost.cshtml
  WebdevPeriod3/Views/Dashboard/_BlogImage.cshtml
  WebdevPeriod3/WebdevPeriod3.csproj
  WebdevPeriod3/wwwroot/js/subsystemlist.js
Labels: bug, enhancement
